language: python
before_install:
- pip install pycodestyle
- pip install pytest
- pip install pytest-cov
- pip install coveralls
- pip install sphinx
- pip install sphinx_rtd_theme
- pip install tpDcc-libs-unittests
install:
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --exclude */externals/* --max-line-length=120
  --ignore=E402 {} +
- pytest --cov=tpDcc
- sphinx-apidoc -f -e -o docs/sphinx tpDcc
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
      password:
    secure: fF/jhPcu/rsElixK8Vxi2KRatHQDdyp9xktqdiWxVxW9m5P2YpVkQRG358n7OWrWclBN9DrwBykh8aPgWgQ2aCxO8yx4B6lhEk7eAbIPpT1KL+LNrN8Ww4spSAz778NGdqjJckVzl/bqwkbIIpIhEfylNBO4OVRKgSG0sjMaXt6sDf6KYJLIH5zeY7OUe0OaBeE7+3UEsjjCnQwkB81B37ntg53mFgbaeY5Wmqjn1DDu5UzZt6MNYa88XkmXMI7TTE1elOCK0vniY8OtwILXX2fnuE9KDTf5G+/39b+R4NDyOz+6lzCHdSkRj2XwYnFVnrEiBD3A9Yu45ikA4TYV00IChLLeC5+zGPWMBo55EPpPhkkU9MC6I8pimkzagjqW4Ngcr30qQrHNsrTsNkrsXgp+mZx849bMaW3p/J2itptODcYI1Hky7q1du5gmqjpz4e0Ncsq8LkFym5p+s4Q9VGrxdH1PVQ1h4kLPsIP3/RO0EsCgdCT8e+CvmkSztUClqy+rC0tz/APcZoJfVQWkxxL50z+euMxnvom+aXHJUDwIHE8keSTgSBBU3XAui8LWX0D5mByg/n3Xl9snj9DDx/l2GITUeMvQ9BM3UkmRaM+5PNFD0B58PTjo8jANkcle0jsogmkZ/EbQdxHymHnUDq0/dWFYN/KWlHHSKu15ZRo=
    on:
      branch: master
      tags: true